### ISSUE TITLE
Волшебные цифры

### ISSUE THREAD

**Issue by ravilASH** [cargovova/PHPCourse#3]
https://github.com/cargovova/PHPCourse/blob/757a694c0d2153bcad93eb872457afbde31f14f9/HomeWorks/hw_3.php#L62

https://ru.wikipedia.org/wiki/%D0%9C%D0%B0%D0%B3%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%BE%D0%B5_%D1%87%D0%B8%D1%81%D0%BB%D0%BE_(%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D0%B5)#%D0%9F%D0%BB%D0%BE%D1%85%D0%B0%D1%8F_%D0%BF%D1%80%D0%B0%D0%BA%D1%82%D0%B8%D0%BA%D0%B0_%D0%BF%D1%80%D0%BE%D0%B3%D1%80%D0%B0%D0%BC%D0%BC%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F

Здесь можно название можно сделать константу НЕПРИЕМЛИМО_НИЗКАЯ_ТЕМПЕРАТУРА

**Comment by cargovova** [comment]
Заменил:
11 на VERY_LOW_TEMPERATURE
13 на LOW_TEMPERATURE
